# Dependencies
markdown:         kramdown
highlighter:      rouge
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               HR Today
tagline:             'Developmental Activities'
description:         'My Personal Blog for HR related activities'
url:                 https://eelafalvi.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Eelaf Alvi
  url:               https://www.linkedin.com/in/eelaf-alvi/
  email:             eelafalvi@hotmail.com

# Custom vars
version:             1.0.0

excerpt_separator: "<!--more-->"

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
